[package]
name = "neural"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.16.0"
bevy = "0.15"
serde_json = "1.0"
rand = "0.8"
bit-vec = "0.6"


